version: 0.0
os: linux

files:  
  - source:  /
    destination: /home/ec2-user/app/back
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
      