import Head from "next/head";
import { Container, Row, Col, Button } from "reactstrap";
import { useRouter } from 'next/router'
import React from 'react';
import Image from "next/image";
import footballimg from "../../../assets/images/landingpage/football.png";
import PartySelect from "../../../components/custom/partyselectform";
import PostMain from "../../../components/custom/board_post/PostMain";
import Link from "next/link";
import { useState } from "react";
export default function Board() {
    const router = useRouter();
    let idcontent =null;
    const {id} =router.query;
    if(id!=undefined){
      idcontent=<PostMain id={`${id}`}/>
    }
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      <Row className="justify-content-center">
          <PartySelect>
          </PartySelect>
                      <Col md="7" className="text-center">
                          <h1 className="title font-bold">Party Title</h1>
                          <h6 className="subtitle">Party 정보글</h6>
                      </Col>
                      <div className="guide_margin">
                      <div className="party_box">
                          {idcontent}
                          
                      </div>
                      <Link href={`/party/${id}/board/write`}>
                          <a className="btn btn-danger m-r-20 btn-md m-t-30 ">
                            글작성
                          </a>
                      </Link>
                      </div>
                  </Row> 
      </Container>
    </div>
  );
}
