import Head from "next/head";
import { Container, Row, Col, Button } from "reactstrap";
import { useRouter } from 'next/router'
import Link from "next/link";
import React from 'react';
import Image from "next/image";
import footballimg from "../../../assets/images/landingpage/football.png";
import PartySelect from "../../../components/custom/partyselectform";

export default function Info() {
    const router = useRouter();
    const { id } = router.query;
    console.log(id);
    const party = {
      party_id:id , // id 외의 정보는 db로 가져오기
      sports_name:'풋살',
      intro:'성북구 풋살을 좋아하고 모임에 관심있는분들 같이파티해요',
      location: '성북구',
      since_date:'2022-4-18',
      title: '성풋모1', 
      infoimg: footballimg
  }
    let partyinfo = {
    manager: '맹구토씈갈리오',
    sinceDate:'2022-4-5',
  }
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      <Row className="justify-content-center">
          <PartySelect>
          </PartySelect>
                      <Col md="7" className="text-center">
                          <h1 className="title font-bold">Party Title</h1>
                          <h6 className="subtitle">Party 정보글</h6>
                      </Col>
                    <div className="guide_margin">
                      <div className="n_guide">
                        <div className="party_infobox" >
                          <div className="my_box">
                            <div className="party_infoboxc">
                              <div className="left_section">
                                <div className="inf_name"><div className="my_font">방장: {partyinfo.manager} 님</div></div>
                                <div className="since_date"><div className="my_font">개설일: {partyinfo.sinceDate}</div></div>
                              <div className="left_buttons">
                                <div className="logout_button">
                                  <div className="my_font">
                                    <Link href="partySignupForm">
                                      파티 가입
                                    </Link>
                                  </div>
                                </div>
                                <div className="logout_button">
                                  <div className="my_font">
                                    <Link href="partyMemberInfo">
                                      파티원 정보
                                    </Link>
                                  </div>
                                </div>
                              </div>
                              </div>
                            </div>
                          </div>
                        </div>                       
                      </div>
                      <div className="n_guide">
                        <div className="party_infobox2" >

                        </div>
                      </div>
                    </div>
                  </Row> 
      </Container>
    </div>
  );
}
