import Head from "next/head";
import PartySignupForm from "../../../components/custom/partysignupform";

export default function PartySignup() {
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PartySignupForm>
      </PartySignupForm>
    </div>
  );
}
