import Head from "next/head";
import { Container, Row, Col, Button } from "reactstrap";
import { useRouter } from 'next/router'
import React from 'react';
import footballimg from "../../../assets/images/landingpage/football.png";
import PartySelect from "../../../components/custom/partyselectform";
import MyCalendar from "../../../components/custom/calendar/MyCalendar"

export default function Schedule() {
  const events = [
    {
        title: "04.24 출근",
        allDay: false,
        start: new Date(2022,3,24,9,0),
        end:new Date(2022,3,24,10,30),
    },
    {
        title: "04.24 퇴근",
        allDay: false,
        start: new Date(2022,3,24,18,0),
        end:new Date(2022,3,24,19,30),
    },
    {
      title: "한성대경기장",
      allDay: false,
      start: new Date(2022,3,24,17,0),
      end: new Date(2022,3,24,19,30),
  },
  {
    title: "고척돔",
    allDay: false,
    start: new Date(2022,3,28,17,0),
    end:new Date(2022,3,28,19,30),
},
];
    const router = useRouter();
    const { id } = router.query;
    console.log(id);
    const party = {
      party_id:id , // id 외의 정보는 db로 가져오기
      sports_name:'풋살',
      intro:'성북구 풋살을 좋아하고 모임에 관심있는분들 같이파티해요',
      location: '성북구',
      since_date:'2022-4-18',
      title: '성풋모1', 
      infoimg: footballimg
  }
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      <Row className="justify-content-center">
          <PartySelect>
          </PartySelect>
                      <Col md="7" className="text-center">
                          <h1 className="title font-bold">{party.title} 일정</h1>
                          <h6 className="subtitle">Party Schedule</h6>
                      </Col>
                      <div className="guide_margin">
                        <MyCalendar event={events} />
                      </div>
                  </Row> 
      </Container>
    </div>
  );
}