spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsmate?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: sks1385!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create-drop
      #???? ???? ????
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true  
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    #type? ????

    #logging
