import Head from "next/head";
import ModifyForm from "../../components/custom/modifyform";

export default function Basic() {
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModifyForm>
      </ModifyForm>
    </div>
  );
}