import Head from "next/head";
import Link from "next/link";
import { Container, Row, Col, Button } from "reactstrap";

export default function Guide() {
  return (
  <div>
       <Head>
        <title>Guide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="guide">
                <Container>
                    <Row className="justify-content-center">
                        <Col md="7" className="text-center">
                            <h1 className="title font-bold">Guide</h1>
                            <h6 className="subtitle">Sports-Mate가 처음이신 사용자들이</h6>
                            <h6 className="subtitle">쉽게 사용하도록 guide를 준비했습니다~ </h6>
                        </Col>
                        <div className="guide_margin">
                          <div className="n_guide">
                            <div className="firstbox" >
                              <h1 className="font_title">Party 이용 가이드</h1>
                              <br></br>
                              </div>
                              
                              
                          </div>
                          <div className="n_guide">
                            <div className="secondbox"><h2 className="font_title">용병 이용 가이드</h2></div>
                          </div>
                          <div className="n_guide">
                            <div className="thirdbox"><h3 className="font_title">결제 서비스 가이드</h3></div>
                          </div>
                        </div>
                    </Row> 
                </Container>
          
       </div>
          
  </div>
  );
};