import Head from "next/head";
import LoginForm from "../components/custom/loginform";
import { Container, Row, Col, Button } from "reactstrap";

export default function Login() {
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm>
      </LoginForm>
    </div>
  );
}
