import Head from "next/head";
import { Container, Row, Col, Button } from "reactstrap";
import RList from "../components/custom/recruitlist";
import {useState} from 'react'



export default function Party () {
  const [mode,setMode]=useState('MYRECRUIT');
  let content = null;
  if(mode == 'MYRECRUIT'){
    content = <RList></RList>
  }
  else if(mode == 'RECRUIT'){
    content = <RList></RList>
  }
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
      <div>
      <Button className="btn btn-md m-t-30 btn-info-gradiant font-14" onClick={(event)=>{
        event.preventDefault();
        setMode('MYRECRUIT');
      }}>
                My Recruit
      </Button>
      </div>
      <div>
      <Button className="btn btn-md m-t-30 btn-info-gradiant font-14" onClick={(event)=>{
        event.preventDefault();
        setMode('RECRUIT');
      }}>
                용병검색
      </Button>
      </div>
      </Row>
      </Container>
      {content}
          
    </div>
  );
};