import Head from "next/head";
import Components from "../components/basic/AllComponents";
import RecruitForm from "../components/custom/recruitform";
export default function Recruit() {
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecruitForm>
      </RecruitForm>
    </div>
  );
}
