import Head from "next/head";
import Link from "next/link";
import React from 'react';
import { Container, Row, Col, Button } from "reactstrap";
import { withRouter } from "next/router"
import Image from "next/image";
const Info = ({ router: {query} }) => {
  try {
    const party = JSON.parse(query.qparty);
    return (
      <div>
           <Head>
            <title>hi</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div id="guide">
                    <Container>
                        <Row className="justify-content-center">
                            <Col md="7" className="text-center">
                                <h1 className="title font-bold">{party.title}</h1>
                            </Col>
                            <div className="guide_margin">
                              <div className="n_guide">
                                <div className="firstbox" >
                                <Image src={party.infoimg} alt="모임소개사진"/>
                                  <br></br>
                                  </div>
                              </div>
                              <div className="n_guide">
                                <div className="secondbox"><h2 className="font_title">{party.location}</h2></div>
                              </div>
                              <div className="n_guide">
                                <div className="thirdbox"><h3 className="font_title">{party.intro}</h3></div>
                              </div>
                            </div>
                        </Row> 
                    </Container>
              
           </div>
              
      </div>
      );
  } catch (err) {
    console.log('Error: ', err.message);
    return (
      <div className="static-slider-head">
        <Head>
          <title>404 - Page not Found</title>
          <meta
            name="description"
            content="The page you are looking for is not found go back to the homepage"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <Row className="justify-content-center">
            <Col lg="8" md="6" className="align-self-center text-center">
              <h1 className="title">404 - Error</h1>
              <h4 className="subtitle font-light">
                The page you are looking for is not available
                <br /> please go back to homepage
              </h4>
              <Link href="/">
                <Button className="btn btn-md m-t-30 btn-info-gradiant font-14">
                  Back to Homepage
                </Button>
              </Link>
            </Col>
          </Row>
        </Container>
      </div>
    );
  }
};
export default withRouter(Info);