import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router'
import PostView from "../../../../../components/custom/board_post/PostView";
import { Container, Row, Col, Form, FormGroup, Label, Input, Button } from 'reactstrap';
import CommonTable from "../../../../../components/custom/board_post/CommonTable";
import CommonTableColumn from "../../../../../components/custom/board_post/CommonTableColumn";
import CommonTableRow from "../../../../../components/custom/board_post/CommonTableRow";
import { useState,useEffect } from 'react';
import axios from 'axios';
export default function Board_id() {
  const router = useRouter();
  const mynickName="장래희망hero"; //db에 토큰으로 내닉네임 요청 
  const { id } = router.query;
  const { board_id } = router.query;
  const [comments,setComments]=useState([]);
    useEffect(() => {
        axios.get(`http://localhost:8080/sportsmate/party/${id}/partyboard/${board_id}/comment`)
        .then(function (response) {
          if(response.status == 200){
            setComments(response.data)
            console.log(response.data)
                                        console.log(comments)
                                    }
                            }).catch(function (error) {
                                    console.log(error);
                                });
    }, []);
  const[text,setText]=useState('');
  const onchangeText = (e) =>{
    setText(e.target.value)
}
 /*{
      comment_id:"1",
      contents:"댓글로 안녕하다고 인사함1",
      since_date:"2022-04-22 14:31:10",
      nick_name:"맹구토슼갈리오1"
    }
    */
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostView board_id={board_id}>  
      </PostView>
                    <div id="view_comment" className="post-view-wrapper">
                    <div className="cmt_box">
                    <div id="comment_count">
                      전체 댓글 {comments.length} 개 [등록순]
                    </div>
                    <CommonTable headersName={['작성자', '댓글내용', '등록일']}>
                        {
                          comments.map(c => {
                            return (
                                <CommonTableRow key={c.id}>
                                <CommonTableColumn>
                                <a>
                                  { c.nickName }
                                </a>
                                </CommonTableColumn>
                                <CommonTableColumn>
                                <a>  
                                  { c.contents }
                                  </a>
                                </CommonTableColumn>
                                <CommonTableColumn>
                                <a>    
                                  { c.sinceDate } 
                                  </a>
                                  
                                  <button id={c.id} value="삭제" onClick={(event)=>{
                                    event.preventDefault();
                                    axios.delete(`http://localhost:8080/sportsmate/party/${id}/partyboard/${board_id}/comment/${event.target.id}`)
                                .then(function (response) {
                                    if(response.status == 200){
                                        alert("댓글이 삭제되었습니다.")
                                        location.reload();
                                }
                            }).catch(function (error) {
                                    console.log(error);
                                });
                                }}>삭제</button>
                                </CommonTableColumn>
                                </CommonTableRow>
                              
                            )
                          })
                        }
                    </CommonTable>
                    <Form id="commentForm" onSubmit={function (event) {
                            event.preventDefault();
                            if(event.target.text.value=='')
                            alert("댓글을 입력해주세요")
                            else{
                            axios.post(`http://localhost:8080/sportsmate/party/${id}/partyboard/${board_id}/comment`, {
                              contents: event.target.text.value 
                            })
                            .then(function (response) {
                              if(response.status == 200){
                                alert("댓글작성완료")
                                location.reload();
                            }
                            }).catch(function (error) {
                              //error
                              console.log(error);
                            });
                            }
                          }
                        }>
                    <Container id="comment_write">
                      <Row id="cmt_write_nickname">
                        <Col md="2">
                        <span>댓글작성</span>
                        </Col>
                      </Row>
                        <Row id="cmt_write_box">
                          <Col md="2" ><span>{mynickName}</span></Col>
                          <Col md="10"><Input type='textarea' className="form-control" id="text" placeholder="댓글을 입력하세요" value={text} onChange={onchangeText}/></Col>
                        </Row>
                        <Row id="cmt_write_bottonbox">
                          <Col md="11">
                          </Col>
                          <Col md="1">  
                          <button type='submit'>등록</button>
                          </Col>
                        </Row>
                    </Container>
                    </Form>
                   </div>
                   </div>
    </div>
  );
}