# workflow 이름
name: Java CI with Gradle

# 이벤트 지정
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
    
# 권한설정 
permissions:
  contents: read

# jobs설
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./back/sportsmate/
      APPLICATION: ${{secrets.APPLICATION}}
      AWS_REGION: ap-northeast-2
      S3_BUCKET_NAME: my-ci-cd-bucket
      CODE_DEPLOY_APPLICATION_NAME: stone-codeDeploy-app
      CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: stone-codedeploy-group

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: make application.yml
      run: |
        mkdir -p ${{ env.working-directory }}src/main/resources  
        echo "${{env.APPLICATION}}" > ${{ env.working-directory }}src/main/resources/application.yml
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run: ./gradlew bootjar
      working-directory: ${{ env.working-directory }}


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY}}
        aws-region: ${{ env.AWS_REGION }}


    - name: Upload to AWS S3
      run: |
        aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --ignore-hidden-files \
          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --source ${{env.working-directory}}.


    - name: Deploy to AWS EC2 from S3
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip

