import React from 'react';
import Head from "next/head";
import { useRouter } from 'next/router'
import PostView from "../../../../components/custom/board_post/PostView";
export default function Board_id() {
  const router = useRouter();
  const { board_id } = router.query;
  return (
    <div>
      <Head>
        <title>Sports Mate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostView board_id={board_id}>  
      </PostView>
    </div>
  );
}